version: '3.8'

services:
  db:
    image: postgres:15 # Or your preferred version
    container_name: tariqi_db
    env_file:
      - .env
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped
  # Add your application service here later if you want to dockerize it
  # app:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env

volumes:
  postgres_data:
    driver: local # Define the volume for persistent data
